version: "3.4"

x-shared-env: &shared-env
  NODE_ENV: "development"
  IS_DOCKER: "true"
  CHOKIDAR_USEPOLLING: "true"

services:
  client:
    build:
      context: ../client
    volumes:
      - ../client:/var/lib/client:delegated
      - /var/lib/client/node_modules/
    ports:
      - "3008:3000"
    environment:
      <<: *shared-env
    container_name: acyclient
    tty: true
    networks:
      - frontend

  server:
    build:
      context: ../server
    volumes:
      - ../server:/var/lib/server:delegated
      - /var/lib/server/node_modules/
    ports:
      - "4008:4000"
    environment:
      <<: *shared-env
    container_name: acyserver
    networks:
      - backend

networks:
  backend:
  frontend:
